export const LOGIN = 'LOGIN';
/* export const LOGOUT = 'LOGOUT';
export const GET_BRANDS = 'GET_BRANDS';
export const GET_CATEGORY = 'GET_CATEGORY';
export const GET_SUBCATEGORY = 'GET_SUBCATEGORY';
export const GET_COUPONS = 'GET_COUPONS';
export const GET_USERS = 'GET_USERS';
export const GET_ADMINS = 'GET_ADMINS';
export const GET_OFFER = 'GET_OFFER';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_QUERY = 'GET_QUERY';
export const GET_BANNER = 'GET_BANNER';
export const GET_SKU = 'GET_SKU';
export const GET_ABOUT = 'GET_ABOUT';
export const GET_DASHDATA = 'GET_DASHDATA';
export const GET_BLOG = 'GET_BLOG';
export const GET_ORDERS = 'GET_ORDERS';
export const SET_LOADING_TRUE='SET_LOADING_TRUE';
export const SET_LOADING_FALSE='SET_LOADING_FALSE'; */
